version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo

volumes:
  mongo_data:
